- name: Backup Config File
  copy:
    src: /etc/zabbix/zabbix_server.conf
    dest: /etc/zabbix/zabbix_server.conf.bak
    remote_src: yes
- name: Modify Config File
  template:
    src: ./zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
  notify:
    - Zabbix Server Config Changed
- name: Start Zabbix Service
  systemd:
    name: zabbix-server
    state: started
    enabled: yes
