- name: Download And Install Agent From Aliyun Mirror Source
  yum:
    name: "{{ Package }}"
    state: present
  vars:
    Package:
      - https://mirrors.aliyun.com/zabbix/zabbix/4.0/rhel/7/x86_64/zabbix-agent-4.0.49-1.el7.x86_64.rpm
      - https://mirrors.aliyun.com/zabbix/zabbix/4.0/rhel/7/x86_64/zabbix-sender-4.0.49-1.el7.x86_64.rpm

